[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.devnet]
oft = "F2D8kmx1ofPJqWYfGrCeV6ZJLSTuZ9XiBodV2fQ1k5H3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/jusikx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
