[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.31"

[features]
seeds = false
skip-lint = false

[programs.testnet]
oft = "ARS9M9JacWPGKhMbWiigXGtvPtwskNBjXg5hGtrniedV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Testnet"
wallet = "/home/jusikx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -b -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
